spring:
  profiles:
    active: alpha
  redis:
    host: localhost
    port: 6379  
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    add-properties: false
  freemarker:
    cache: false
  jwt:
    secret: govlepel@$&